name: Setup Nix
description: Sets up Nix with optional caching

inputs:
  enable-cache:
    description: Enable nix-cache
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Enable Nix cache
      if: inputs.enable-cache == 'true'
      uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        use-flakehub: false
